title: Tooters.org
tagline:
url: https://home.tooters.org
baseurl: ""
permalink: :title/

timezone: America/New_York

kramdown:
    footnote_backlink: "&#10548;"

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Victor Wynne
  url: https://tooters.org 
  email: victor@tooters.org

version: 1.4.0
github:
  repo: https://github.com/victorwynne/quattle/

# Feed
name: Tooters
description: Tooters.org
url: https://home.tooters.org
