title: Verification by Tooters
tagline:
url: https://jessica.tooters.org
baseurl: ""
permalink: :title/

timezone: America/New_York

kramdown:
    footnote_backlink: "&#10548;"

plugins:
  - jekyll-seo-tag
  - jekyll-target-blank

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Jessica Rae
  url: https://jessica.tooters.org 
  email: verification@tooters.org

version: 1.4.0
github:
  repo: https://github.com/victorwynne/quattle/

# Feed
name: Verification by Tooters
description: Verification by Tooters
url: https://jessica.tooters.org
